panic bot vote tracking - panic ban
streemtech/panicbot pull request #11
Opened 2022-08-20 09:02 UTC by Xanzibaer

Co-authored-by: Bradley Andrew Marques
Co-authored-by: deef

2022-08-21 00:06 UTC, deefdragon requested changes

2022-08-21 00:06 UTC, deefdragon commented on discord.go
> +		return nil, fmt.Errorf("failed to send welcome message")
wrap the error here so that we pass it on.

2022-08-21 00:06 UTC, deefdragon commented on discord.go
> +	//TODO verify if return values can be simplified
remove this todo. Gami did the thing.

2022-08-21 00:06 UTC, deefdragon commented on cmd/panicbot/main.go
>  	// This function will be used to tally up the votes and then take action.
These cab be removed now.

2022-08-22 20:52 UTC, bradleyGamiMarques approved these changes

2022-08-22 20:53 UTC, bradleyGamiMarques approved these changes

2022-08-22 20:57 UTC, deefdragon approved these changes

2022-08-22 21:03 UTC, merged